apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: movie-rater
type: Opaque
data:
  DB_USER: bW92aWU=
  DB_PASSWORD: cGFzc3dvcmQ=
  PUBLICKEY: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxN1llMmdCbEpTM3U1dnk1UnFmdUZSZE1aVmg2MG1yZ3RMcXhySHhNa2tNU0V1cVJ6a05va0QwY29NNEJhVUtDSmQrM254ektndWZWNEhhNHRXdDZScHlod1dUVU53MzJaZlFTNFZ2LzNyS0NyZFNoZW1wMjdXM3UzZTQwK2xCVjJqdlk4cmQ0WUp2Yy9CTVZwbGI2M3VXbmlCQjQwZ1I4aFlIdDZuU2UzMTZHcXFxZnljNy9Td3g0S3N1UzY2NXlYMnlxM3o3S3ZKRWM1bGdlTXlmK3R6T2MydDBQbythcFlvOHZYMjBGTnRsa29pSWo1Tk5Pb0xteFdUZ0JpM1liSW1TWjZOWnlUelFKYWtYV1E3YWlzNkd4U056MGUwZ2FrSTYxNnpKYXhXZVZ0V2crZFFVYnBpVXk5dFo2TFltNHZTUmJXMmt6TkI0VG9wYjNmY29CMHdJREFRQUI=