apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: movie-rater
type: Opaque
data:
  DB_USER: bW92aWU=
  DB_PASSWORD: cGFzc3dvcmQ=
  PUBLICKEY: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtNGJsbVdYTXRYTS81WXlMVEtEemNEUVZVZnh2ZWJwL0ZOTjBJZmJ5REIrS3hmaHRNQnE5cHNYYm5Ob250MXdma1JNUWltR1YyT1E4cFBUSDRaRnVpV1M0SHgzMkRwR0dXem1RV0JRNzlGUlNjeExBN0UyYnV4WU5ZM0paZWd6dm1iWFpjelJLeGMvZW5HVjcwVFFyL1B1YUtpTmkrVWpZeFRtUWZWOXJ3ekJLdzhNQklJeGltc0tzd0VDTzV0aTVnVGJHcXhVTmd3Y1hNZ3FFNDltK1lkZXU3eTdoUS9HVytONEVYRC8xZEtWTm4zMjRyV2xTTG1Gc2Y0NkhJMCtTV3gxRzF2RnVjMXZ3WllaK3FNOXc0b00wdmZrQmJxV1MrQStvRUFVcUhTZ3NWRXR2c2ZwZjMvU3dPRXh6SEJUNnord24vWFFXUjdJNjBPOUhyb2ttNFFJREFRQUI=