apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: movie-rater
type: Opaque
data:
  DB_USER: bW92aWU=
  DB_PASSWORD: cGFzc3dvcmQ=
  PUBLICKEY: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5TlpockQrZWdlazNRZjl4cU1rNENDVVVkTHNyaExmSFJaOG94bkUreUdPQ2d0VGQvTTI2TlNCMzY2WHdRUUE5blRhNkZ6eVE4TEIxYitZWkhKRVlEMnl5VUVoaXd5NWtSZmFEZkx4ZDRWdmMrdUpzcEZibFNGcjlxTDJrVHhhVTRSdzlueUdqNWs2dWlXVTBYTG9SZkJCb2FkSExESkxJM2VYVVY2a0xlYmJVai96WlFCaXh2aE5WQWRIQy9yVVZhVG1Bckt5aE5SU3FxVDJwSGVwMzFncmZsRGVmMis5MzZmOVFMYjRUUzFidmhJSkhxbGdKSnovVnlIaFJvUEppNTZST2tHVG1xL05FeWtIWVF3eWJVbVJYa2YzSW9PcmRaMURKeFpBUjJGaVNKOEJKd2dKZVFmNS8vRG9aWFBCMWtpWHpQSGJYT2FrTzlZYzBPNG5COHdJREFRQUI=