worker_processes auto;

events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60s use_temp_path=off;
    client_body_temp_path /tmp/client_temp;

    upstream backend-server {
        server backend:3000;
    }

    server {
        listen 8080;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        location /api/ {
            proxy_pass http://backend-server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, POST";
        }
    }
}