services:
  frontend:
    build: ./app/frontend
    container_name: frontend
    ports:
      - 80:8080
    configs:
    - source: nginx_config
      target: /etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./app/backend
    env_file: ./app/backend/.env
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    container_name: movie_postgres
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
      POSTGRES_DB: movie
    volumes:
      - movie_data:/var/lib/postgresql/data
      - ./app/backend/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  movie_data:

configs:
  nginx_config:
    file: ./app/frontend/nginx/nginx.conf