apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  env.js: |
    window.__ENV__ = {
      KEYCLOAK_URL: "https://auth.movie-rater.local",
      KEYCLOAK_REALM: "master",
      KEYCLOAK_CLIENT: "movie-rater"
    };