apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-rater-ingress
  namespace: movie-rater
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - movie-rater.local
    - auth.movie-rater.local
    secretName: tls-secret

  rules: 
  - host: movie-rater.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3000

  - host: auth.movie-rater.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080